In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Rahul", "Sneha", "Arjun", "Priya", "Karan"],
    "Salary": [45000, 60000, 52000, 48000, 70000],
    "Department": ["HR", "IT", "Finance", "IT", "HR"]
}

df = pd.DataFrame(data)
df

    Name  Salary Department
0  Rahul   45000         HR
1  Sneha   60000         IT
2  Arjun   52000    Finance
3  Priya   48000         IT
4  Karan   70000         HR

In [3]:
df[["Name", "Salary"]]

    Name  Salary
0  Rahul   45000
1  Sneha   60000
2  Arjun   52000
3  Priya   48000
4  Karan   70000

In [4]:
df[df["Salary"] > 50000]

    Name  Salary Department
1  Sneha   60000         IT
2  Arjun   52000    Finance
4  Karan   70000         HR

In [5]:
df.groupby("Department").size()

Department
Finance    1
HR         2
IT         2
dtype: int64

In [6]:
df.sort_values(by="Salary")

    Name  Salary Department
0  Rahul   45000         HR
3  Priya   48000         IT
2  Arjun   52000    Finance
1  Sneha   60000         IT
4  Karan   70000         HR